### ISSUE TITLE
Error reading map-make.js

### ISSUE THREAD

**Issue by simsala** [pilgrimdb/pilgrimdb.github.io#20] opened 2016-06-22 11:13 UTC
I seem to be getting an error 'Error reading map-make.js' whenever I click on any map in any of the routes on this page.

Example:
https://pilgrimdb.github.io/maps.html?feature=osm/1622

gives me a:
'Error reading map-make.js' 

Tested with Safari and Firefox on macOS.

**Comment by probins** [comment] 2016-06-22 12:15
sorry about that; should be fixed now

**Closed as completed by probins** 2016-06-22 12:15 UTC

**Comment by simsala** [comment] 2016-06-23 13:02
Thanks, seems to be working now.
But: did you remove the links?

It seems to me I can no longer find the page that had lead me to this page:
https://pilgrimdb.github.io/maps.html?feature=osm/1622

Thanks

**Comment by probins** [comment] 2016-06-23 14:58
that seems to be a different problem: the map links have indeed all disappeared. I will investigate

**Comment by probins** [comment] 2016-06-23 15:35
hmm, that was caused by a change in behaviour in the software that generates the site. Now also fixed. The page you found the link on will have been https://pilgrimdb.github.io/potsdam.html

**Comment by simsala** [comment] 2016-06-24 06:04
Hello Peter

Thanks for fixing it. 

One other question:
Why is it you no longer provide direct downloads?
You still seem to have the data so that you could easily share them in GPX or KML format.
It's a pity you don't.

Kurt

Sent from my iPad

**Comment by probins** [comment] 2016-06-24 06:25
there are downloads, in GeoJSON. This is a static site, so GPX/KML files would have to be recreated every time the site was changed. There are currently 2700 files, so an extra 5400 files would have to be created - and that's out of date; if the site included all the currently unmapped routes plus all the new routes, the number would be well over 6000.

**Comment by simsala** [comment] 2016-06-24 06:41
Thanks

But the GeoJSON to me seems a very unusual format to use.
It is a very uncommon format and is not easy to convert to GPX or KML.

Even GPSBabel does not seem to support it.

Kurt

**Comment by probins** [comment] 2016-06-24 06:43
http://converter.mygeodata.eu/ for example

**Comment by probins** [comment] 2016-06-24 06:48
alternatively, you can load it in the map program, add the draw component, and then output as kml/gpx

**Comment by simsala** [comment] 2016-06-24 06:54
thanks.
but what's the advantage of using the GeoJSON format against for example gpx in first place?

**Comment by probins** [comment] 2016-06-24 07:13
simpler, smaller, supported by GitHub

**Comment by simsala** [comment] 2016-06-24 07:18
ok.
to me still seems a very uncommon way to go.

gpx is supported everywhere.
no conversion needed.

surely size is not an issue.

GeoJSON has to be converted for everything.

I don't really understand this decision…

**Comment by probins** [comment] 2016-06-24 08:15
GeoJSON is widely supported by mapping software (it's the default for OpenLayers, which is what the map program uses); it also fits in with the GitHub flow. If someone submits a change to https://github.com/pilgrimdb/pilgrimdb.github.io/blob/master/_includes/geometries/1622.geojson for example, because GitHub displays the file as a map, you can see at a glance what has been changed. This is impossible using gpx or kml or any other format.
